name: challecara
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.3.0
  http: ^0.13.3
  google_maps_flutter: ^2.0.6


  hooks_riverpod: ^2.5.1
  settings_ui: ^2.0.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

# l10nセクションをflutterの外に置きます。
l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
