name: challecara
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.5.1
  settings_ui: ^2.0.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.2
  intl: ^0.19.0
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  google_maps_flutter: ^2.9.0
  provider: ^6.1.2
  flutter_spinkit: ^5.2.1
  flutter_math_fork: 0.7.2

  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0  # 最新バージョンを確認して置き換えてください
  firebase_auth: ^5.3.3   # 最新バージョンを確認して置き換えてください
 # flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - images/
    - assets/image.png
    - .env
