// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsuwb8Xg0XB7tHfmf5vSvABfXVCIs6Yl0',
    appId: '1:863182911737:web:3d756e62ed7634a83b0a28',
    messagingSenderId: '863182911737',
    projectId: 'aruke-ru-v2',
    storageBucket: 'aruke-ru-v2.firebasestorage.app',
    authDomain: 'aruke-ru-v2.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsuwb8Xg0XB7tHfmf5vSvABfXVCIs6Yl0',
    appId: '1:863182911737:android:dd57df97555959c93b0a28',
    messagingSenderId: '863182911737',
    projectId: 'aruke-ru-v2',
    storageBucket: 'aruke-ru-v2.firebasestorage.app',
    authDomain: 'aruke-ru-v2.firebaseapp.com',
  );
}
